version: "3.8"

services:
  rn-nginx-proxy:
    image: nginx:stable-alpine
    container_name: rn-nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # restart: 'unless-stopped'
    restart: "always"
    networks:
      - rn-backend
  rn-express-server:
    build:
      context: ./Express
      args:
        NODE_ENV: development
      target: rn-development-build-stage
      dockerfile: Dockerfile
    container_name: rn-express-server

    # Remove volumes in prod because it doesn't respect .dockerignore
    volumes:
      - /app/node_modules
      - ./Express:/app
    # restart: 'unless-stopped'
    restart: "always"
    networks:
      - rn-backend

  # rn-graphql-server:
  #   build:
  #     context: ./Graphql
  #     args:
  #       NODE_ENV: development
  #     target: rn-development-build-stage
  #     dockerfile: Dockerfile
  #   container_name: rn-graphql-server

  #   # Remove volumes in prod because it doesn't respect .dockerignore
  #   volumes:
  #     - /app/node_modules
  # - ./Graphql:/app
  #   # restart: 'unless-stopped'
  #   restart: "always"
  #   networks:
  #     - rn-backend
networks:
  rn-backend:
    driver: bridge
# docker-compose down -v
# keep docker and nginx files in main backend folder and proxy pass to express and graphql. And it seems like the load balancing, microservice and multi container

# 1. docker-compose up => just starts the container/create and starts if new
# 2. docker-compose build => starts container with file changes read => use this when file changes
# 3. docker container prune => removes all stopped containers
# 4. docker exec -it NAME_OF_THE_CONTAINER bash => opens the interactive bash
# 5. docker run -it NAME_OF_THE_IMAGE => run the respective image

#==========================
# UPDATE PACKAGE FREQUENTLY
# USE NODE VERSION 14
#==========================
